### PR TITLE
Python3 / Django2.2

### PR DESCRIPTION
**Pull request by BrianPainter**
Upgraded to Python3 and Django 2.2 LTS

cleaned up the requirements file, and upgraded packages.

### CODE REVIEW

**Comment by BrianPainter** [comment]
If you don't mind adding the 'hacktoberfest-accepted' label to this pull request so that it can "count" towards hacktoberfest goals, that would be swell!

**Review by brylie — CHANGES_REQUESTED** [review]
Please remember to remove the redundant `get_environment_variable` function.

**Review by BrianPainter — COMMENTED** [review]
@brylie I removed the get_env_variable function here, and replaced it with django_environ throughout the file.

**Comment by brylie** [comment]
Ah, my bad. I overlooked that.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @BrianPainter for code

**Pull request merged**
