### PR TITLE
Remove waffle.io badge from README

### PR DESCRIPTION
**Pull request by NdagiStanley**
I'm aware of this [PR](https://github.com/CiviWiki/OpenCiviWiki/pull/777) and this [issue](https://github.com/CiviWiki/OpenCiviWiki/issues/770)

This PR is to have the change reflect on the default branch `dev`

### CODE REVIEW

**Comment by BrianPainter** [comment]
Do we have a documented process for merging dev into master on a regular basis?

**Comment by NdagiStanley** [comment]
Any word on this?

**Comment by brylie** [comment]
@NdagiStanley I'm sorry for the delay on this pull request. I didn't get a notification that it had opened.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @NdagiStanley for docs

**Pull request merged**
