### PR TITLE
Add's flask linting to CI

### LINKED ISSUE #1033: {RFC} Requirement of Actions to enforce Code Formatting.
### Idea summary

We need a code-formatter

### Further details

I think it is high time we start using flake, autopep8 or black. I am personally inclined to use black but if there are standards which the project adapts, I shall make amends.

### PR DESCRIPTION
**Pull request by wassafshahzad**
Closes #1033

### CODE REVIEW

**Review by AbhijithGanesh — APPROVED** [review]
These changes work completely fine, the tests are failing due to unused imports,nothing related to this PR

**Review by brylie — CHANGES_REQUESTED** [review]
Please ensure the `flake8` settings are compatible with `black` defaults:

```yaml
- name: flake8 Lint
  uses: py-actions/flake8@v1
  with:
    extended-ignore: "E203"
    max-line-length: "88"
```

**Comment by brylie** [comment]
@wassafshahzad, thanks for this contribution. Would you mind making the small changes requested above?

**Comment by znhv** [comment]
Can I help?

**Comment by brylie** [comment]
@znhv, yes, please. You will need to create a branch from @wassafshahzad's branch, in order to preserve attribution.

**Comment by wassafshahzad** [comment]
I will complete this by tonight hopefully 
 I'm a bit stuck at work lately

**Comment by znhv** [comment]
Ready?

**Comment by brylie** [comment]
@znhv go ahead and open a new pull request from your branch. That way, we will have all commits from @wassafshahzad and you.

**Comment by wassafshahzad** [comment]
> Ready?

Make sure it excludes migrations and test files

**Pull request merged**
