### PR TITLE
Remove U.S.-centric code from the project

### PR DESCRIPTION
**Pull request by xsraut**
- Removed U.S. related code.
- Created Database Migrations

### CODE REVIEW

**Comment by gorkemarslan** [comment]
@xsraut, I am converting this PR to draft. After all mentioned issues in #1106 are solved, this PR will be ready to review.

Could you also edit your PR message to link this PR to issue #1106?


[Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).
> 
> close
> closes
> closed
> fix
> fixes
> fixed
> resolve
> resolves
> resolved

**Comment by xsraut** [comment]
> @xsraut, I am converting this PR to draft. After all mentioned issues in #1106 are solved, this PR will be ready to review.
> 
> Could you also edit your PR message to link this PR to issue #1106?
>
> [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> 
> > You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).
> > close
> > closes
> > closed
> > fix
> > fixes
> > fixed
> > resolve
> > resolves
> > resolved

**Comment by gorkemarslan** [comment]
@xsraut, could you put check marks on the checkboxes in issue #1106? That would make it easier for us to be sure that all task are done. You can click the completed boxes via your `mouse` for this purpose.

**Comment by brylie** [comment]
When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Comment by brylie** [comment]
I'm converting this pull request to draft status since there is still work in progress.

**Comment by gorkemarslan** [comment]
Fixed by #1141

**Pull request closed without merging**
