### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Minor bug fixes in the project (I haven't created an issue for this because it doesn't come under one umbrella issue)

### CODE REVIEW

**Review by gorkemarslan — APPROVED** [review]

**Comment by AbhijithGanesh** [comment]
Will this be considered for hacktoberfest?(I don't think I have a problem with hacktoberfest but just asking @brylie )

**Review by gorkemarslan — CHANGES_REQUESTED** [review]
@AbhijithGanesh, could you fix what PEP8 says:

> In the file project/categories/models.py:
> Line 15:1: W293 blank line contains whitespace
> Line 17:43: W292 no newline at end of file
> 
> In the file project/threads/models.py:
> Line 473:1: W293 blank line contains whitespace

**Comment by AbhijithGanesh** [comment]
I'm so sorry but I just packed my setup, can you please commit them if possible ? I'm not sure whether you can do it or not but brylie can... Sorry for this😅

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, let me try. 😄

**Review by gorkemarslan — APPROVED** [review]

**Comment by AbhijithGanesh** [comment]
@brylie can you merge this

**Review by brylie — APPROVED** [review]

**Pull request merged**
