### PR TITLE
Reduce unnecessary requirements.

### PR DESCRIPTION
**Pull request by TomaszKolek**
Its first step to updating dependencies. I noticed the project had too many dependencies (I believe someone created this file based on pip freeze where we have all of the packages like dependencies of dependencies)

This PR requires testing on some dev server or running e2e tests

### CODE REVIEW

**Comment by brylie** [comment]
Looks good. Add the 'ready for review' label when this is ready.

**Comment by TomaszKolek** [comment]
Its done, could you run e2e or check it on dev server?

Also could you please write instruction on how to run e2e - it'd be easier to test it on my end later.

**Comment by TomaszKolek** [comment]
@brylie were you able to check it? It'd be great start point before docker to avoid any mess with historical commits.

**Comment by brylie** [comment]
@Unit111, we are having difficulty running the automated tests you provided us. Could you please provide a brief description of how to run the tests?

**Pull request merged**
