### PR TITLE
pre-commit should be installed before using it

### PR DESCRIPTION
**Pull request by coderrohanpahwa**
:warning: When contributing code, please make sure you claim any related issue before opening a pull request. We will then assign you to the task to let other developers know that it has been claimed.

Closes #issue-number

### CODE REVIEW

**Comment by brylie** [comment]
@coderrohanpahwa, thank you for your contribution. Please open an issue first to discuss the problem related to this PR.

I believe we just need to add `pre-commit` to our dev dependencies using `poetry add pre-commit --group dev` rather than installing to the global Python environment.

**Review by brylie — CHANGES_REQUESTED** [review]
@coderrohanpahwa, thank you for your contribution. Please open an issue first to discuss the problem related to this PR.

I believe we just need to add pre-commit to our dev dependencies using poetry add pre-commit --group dev rather than installing to the global Python environment.

**Comment by coderrohanpahwa** [comment]
Hi @brylie, I have opened the issue. Kindly check

**Comment by brylie** [comment]
Closing as superseded by #1404

**Pull request closed without merging**
