### PR TITLE
Sync congress.json with current representative model

### LINKED ISSUE #542: "Representative has no field named 'first_name'" - error when running "loaddata data/congress.json"
When running the following command:

>python project/manage.py loaddata data/congress.json

I get this error:

`Problem installing fixture '/app/data/congress.json': Representative has no field named 'first_name'`

I'm on a Mac running Mojave 10.14.5
Using the Docker setup

I will work on creating a video with a fresh `git clone` now.

### PR DESCRIPTION
**Pull request by umr55766**
Fixes #542 

Screen Shot 2019-08-19 at 10 40 56 PM

### CODE REVIEW

**Comment by umr55766** [comment]
Yes I have verified that the keys of this JSON is same as those returned by ProPublica. But ProPublica is returning few more data which we don't have here in this JSON.

```
[
  {
    "bioguide_id": "B001291",
    "name": "Brian Babin",
    "state": "TX",
    "chamber": "House",
    "district": 36,
    "party": "R",
    "slug": "B001291-brian-babin",
    "start_date": "2019-01-03",
    "end_date": "2021-01-03"
  },
  {
    "bioguide_id": "C001056",
    "name": "John Cornyn",
    "state": "TX",
    "chamber": "Senate",
    "district": "Sen.",
    "party": "R",
    "slug": "C001056-john-cornyn",
    "start_date": "2019-01-03",
    "end_date": "2021-01-03"
  },
  {
    "bioguide_id": "C001098",
    "name": "Ted Cruz",
    "state": "TX",
    "chamber": "Senate",
    "district": "Sen.",
    "party": "R",
    "slug": "C001098-ted-cruz",
    "start_date": "2019-01-03",
    "end_date": "2021-01-03"
  }
]
```

**Comment by brylie** [comment]
@all-contributors please add  @umr55766 for code

**Comment by brylie** [comment]
Thanks @umr55766 :-)

**Comment by umr55766** [comment]
@brylie I am interested in contributing more, if there is something I can help with, kindly let me know. My Django skill is of moderate level.

**Comment by brylie** [comment]
Thanks. See if any of the Help Wanted tasks would be a good fit:
https://github.com/CiviWiki/OpenCiviWiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Pull request merged**
