### PR TITLE
Anuragwiki

### PR DESCRIPTION
**Pull request by anurag629**
I have removed the wrong python syntax

### CODE REVIEW

**Comment by anurag629** [comment]
sir, please review my PR

**Review by brylie — CHANGES_REQUESTED** [review]
Please add a meaningful title and description to this pull request. What issue(s) does it solve?

There are many conflicts here. Please consider closing this pull request and applying your changes against the latest `develop` since these changes may already be included in the project.

**Comment by anurag629** [comment]
I forgot to update my branch and also I am not aware that a notification app has already been created or not.
So I created a notification app and makes a PR for that. Next time I will update my branch before making any changes in the codebase.

Thanks!

**Comment by brylie** [comment]
@anurag629 you can delete the old branch since these changes have already been merged. Make sure to [sync your fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) with the recent changes.

**Pull request closed without merging**
