### PR TITLE
Fixes #36 Fixes #37 Consistent spacing updates

### LINKED ISSUE #36: Use consistent spacing and indentation (Flake8 errors)
After running Flake8 (#33), we received several notices about **spaces and indentation** in CiviWiki sourcecode.

# Goal
Use consistent indentation and spacing throughout CiviWiki sourcecode. Conform to guidelines of PEP-8.

# Task
Clean up the following Flake8 errors:

- [x] ./api/read.py:220:60: E272 multiple spaces before keyword                                                                                                                                                                                                                      
- [x] ./api/read.py:220:87: E272 multiple spaces before keyword
- [x] ./api/write.py:499:19: E271 multiple spaces after keyword
- [x] ./api/write.py:502:58: E225 missing whitespace around operator
- [x] ./api/write.py:549:19: E271 multiple spaces after keyword
- [x] ./api/models/civi.py:41:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:41:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:43:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:54:31: E251 unexpected spaces around keyword / parameter equals
- [x] ./api/models/civi.py:65:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:65:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:67:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:116:29: E241 multiple spaces after ':'
- [x] ./api/models/civi.py:124:5: E301 expected 1 blank line, found 0
- [x] ./api/models/civi.py:156:39: E225 missing whitespace around operator
- [x] ./api/models/civi.py:156:42: E221 multiple spaces before operator
- [x] ./api/models/civi.py:166:48: E225 missing whitespace around operator
- [x] ./api/models/civi.py:190:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:190:1: W191 indentation contains tabs
- [x] ./api/models/civi.py:191:1: E101 indentation contains mixed spaces and tabs
- [x] ./api/models/civi.py:208:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./api/models/account.py:88:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./api/models/account.py:169:5: E301 expected 1 blank line, found 0
- [x] ./api/models/thread.py:57:1: E305 expected 2 blank lines after class or function definition, found 1
- [x] ./authentication/forms.py:121:297: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:299: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:316: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/forms.py:121:318: E251 unexpected spaces around keyword / parameter equals
- [x] ./authentication/authentication.py:29:5: E301 expected 1 blank line, found 0
- [x] ./authentication/authentication.py:39:1: E305 expected 2 blank lines after class or function definition, found 1

### LINKED ISSUE #37: Move all imports to top of file
As part of our clean-code conventions, all imports should be at the top of their file.

# Goal
Move all imports to top of their file. No import errors when running Flake8 (#33).

# Task
The following imports should be moved to the top of their file:

- [x] ./civiwiki/wsgi.py:14:1: E402 module level import not at top of file
- [x] ./civiwiki/wsgi.py:15:1: E402 module level import not at top of file

### PR DESCRIPTION
**Pull request by mattyg915**
Closes #36 
Closes #37 

Removing extra spaces, changing mixed indentations to only use tabs, adding blank lines beneath function or class definitions, adding spaces around operators

### CODE REVIEW

**Comment by brylie** [comment]
Let us know when this is ready for review.

**Comment by mattyg915** [comment]
Sorry! Crazy busy few days. This PR fixes Issues #36 and #37

**Comment by brylie** [comment]
> This PR fixes Issues #36 and #37

Add that note to the issue **description** like so:

> Fixes #36 
> Fixes #37

That way, GitHub and Waffle will link the PR to the issues.

**Comment by mattyg915** [comment]
I'm sorry, I'm apparently not smart enough to figure out how to edit the description. Is putting the fixed issue numbers in the title enough (it seems to say that's one way to do the association in the article you linked), or should I make another commit where I don't change anything, but include the issue link in the description? I don't seem to be able to edit the commit descriptions, which was another way the article said to link them.

**Comment by brylie** [comment]
You are editing the PR *title*. The **description** is pretty much the first comment in this thread. Just press the pencil button next to the smiley face, and you can edit the text.

Since this PR is closing multiple issues, it is better to edit the description rather than the title. Closing a single issue from the title will work, but we can link multiple issues in the description like so:

```
Closes #123
Closes #234
```

**Comment by mdwest** [comment]
Is this ready to be merged?

**Comment by brylie** [comment]
@mattyg915 this looks good. Are you finished working in this branch?

**Comment by mattyg915** [comment]
Yep! I'm done with the branch. Should I delete it after it's merged?

**Comment by mdwest** [comment]
@mattyg915 I just wanted to update you on the project. We just finished a QA review and opened a chunk of new issues. I was wondering you are interested in helping us fix some of our ID problems for example https://github.com/CiviWiki/OpenCiviWiki/issues/130

**Pull request merged**
