### PR TITLE
Show bills under legislation header.

### PR DESCRIPTION
**Pull request by TomaszKolek**

### CODE REVIEW

**Comment by brylie** [comment]
@mdwest can you review the UX for this PR with @TomaszKolek ?

**Comment by mdwest** [comment]
I'm not seeing this UX on the test server. Is it merged?

**Comment by TomaszKolek** [comment]
@mdwest I think you did. Its a Linked bills part you sent a screenshot with

**Comment by TomaszKolek** [comment]
@brylie I think @mdwest already reviewed it.

**Comment by brylie** [comment]
@mdwest should this PR be merged, or did you have any change requests?

**Pull request merged**
