### PR TITLE
Altering Civi

### LINKED ISSUE #1101: Make `linked_civis` and `response_civis` fields optional on Civi model
The `Civi` model contains two required fields that are causing difficulty when starting a fresh project:

- `linked_civis` https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L214
- `response_civis` https://github.com/CiviWiki/OpenCiviWiki/blob/85cd5bf867be4e1987cff3f083fc456904287f9e/project/threads/models.py#L215-L221

Since those fields are required, it is not possible to create the first Civi, due to the "chicken and egg" situation where no Civis exist.

## Task

- [x] remove the `response_civis` field
- [x] make the `linked_civis` field optional
- [x] create database migrations with `python manage.py makemigrations`

## Original report
@AbhijithGanesh opened this issue originally with the following information.

### Description

Without fixtures in Civi, it is not possible to create Civis and it is requires a civi to be referenced when created, which makes it impossible to create.

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Closes  #1101

### CODE REVIEW

**Comment by brylie** [comment]
If this pull request doesn't close issue #1101, split the issue into sub parts so that one part can be closed fully by this pull request. Otherwise, use a GitHub keyword to automatically link this pull request to an issue, as outlined below.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Comment by AbhijithGanesh** [comment]
Btw can you review this please?

**Comment by brylie** [comment]
> Btw can you review this please?

Please follow the instructions below to link this pull request to the related issue.

When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Review by brylie — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by brylie** [comment]
Converting to draft while waiting for resolved conflicts.

**Comment by AbhijithGanesh** [comment]
Those changes aren't conflicting and GH is incorrect.

**Comment by AbhijithGanesh** [comment]
image

I genuinely don't understand why github should throw a conflicting file for a newline, this is weird.

**Review by brylie — CHANGES_REQUESTED** [review]
There are still conflicts. Follow the [GitHub documentation to resolve the conflicts via command line](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line).

image

**Comment by AbhijithGanesh** [comment]
Those conflicting files have been merged using the same, you can see the differences w.r.t to the original also

**Review by brylie — CHANGES_REQUESTED** [review]
It looks like there are changes in this pull request that aren't related to issue #1101. In effect, the only changes should be

image

Did the changes in this branch come from a work-in-progress branch related to a different pull request?

**Comment by AbhijithGanesh** [comment]
It comes from my branch because I created changes for #1122  first then I merged it with my develop then created this branch

**Comment by AbhijithGanesh** [comment]
Even if I didn't merge, these changes would show up

**Comment by AbhijithGanesh** [comment]
After the merging of PR #1122, the common changes should vanish

**Comment by brylie** [comment]
> Even if I didn't merge, these changes would show up

If your branch was based on `develop`, the changes wouldn't show up since there would be no differences from the `develop` branch.

**Comment by brylie** [comment]
Just remember to start all new work branches from the latest `develop`. It will save some hassle :smiley:

**Comment by AbhijithGanesh** [comment]
I have closed this for the same

**Pull request closed without merging**
