### PR TITLE
Added and edited docstrings to all functions and classes

### PR DESCRIPTION
**Pull request by North15**
This is in reference to Issue #21 
@brylie If you could take a look and let me know if you'd like anything else changed.

Thanks

### CODE REVIEW

**Comment by North15** [comment]
There were a few places where I was unsure exactly what the function or class was doing so I added """ """ but left them empty. Let me know if this is an issue and I'll go back and remove them.

**Comment by brylie** [comment]
@North15 please resolve conflicts.

Specifically,
- delete `project/api/consumers.py` as it is no longer needed (until we need real-time functionality)
- `authentication.py` and `forms.py` have been over to `/project/accounts/`

**Review by brylie — CHANGES_REQUESTED** [review]
The docstrings look good.

Please resolve conflicts by removing the conflicting files. They have all been moved or deleted.

**Comment by brylie** [comment]
@all-contributors please add @North15 for code

**Pull request merged**
