### PR TITLE
Updates to frontend-views

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Addresses #1090 and sticks to convention

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
@brylie and @gorkemarslan , let this issue be sidelined as it would be affected once other PRs are merged. I will rework once Brylie merges other PRs.  Thank you😄

**Comment by AbhijithGanesh** [comment]
If this is closed, it'll be lost in tracks, can this be made as a draft

**Review by brylie — CHANGES_REQUESTED** [review]
We don't need to lint/format Django migrations. Please restore the original formatting for Django migrations so this pull request is easier to review.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, it would be better if we close this PR.

In issue #1090, it is written:

> Please start this issue after merging PR #1088 and #1089.

to avoid from conflicts because the issue #1090 heavily depends on the changes that two PRs do. So this was purposely said. :smile: 

I want to some other points:

You committed:

> Updated categories to faciliate load data

You created this branch from the one #1082. So you included changes that are not related to the issue #1090. If I am not wrong, you did the same once again. You can make mistakes, this is completely ok. :smile: We all do and welcome well all kind of mistakes. To avoid from the similar mistake, I suggest you my way. Sometimes I make silly mistakes when using Git. :smile: 

[PyCharm](https://www.jetbrains.com/pycharm/) serves a powerful Git management. I strongly recommend you to use it. Before pushing commits, it really helps me a lot. @brylie do you have any recommendation for Git management? Are you using any useful tool to help us? :sweat_smile: 

@AbhijithGanesh, you made changes what #1088 is supposed to do. At some point, you realized it and restored them. You committed both changes. In a similar situation, please undo your last commit by using `git revert HEAD` ([ref](https://stackoverflow.com/questions/927358/how-do-i-undo-the-most-recent-local-commits-in-git)). Or PyCharm provides undo commit functionality.

Solution of issue #1090 is not expected to change in migrations. Please not to do anything about migrations. :smile: 

And run `flake8` before committing to check your code format.

Finally, I want to close this PR not because of the mistakes. You're okay to make any mistake again. :smile: The real reason is that in the future when we want to look at the issue #1090 and its solution (this PR), we'll see that there are some changes in migrations. The url files are also changed multiple times (`url()` to `path()` and `path()` to `url()`). 

So not only your code should be clear and have good quality, but also your PR. Otherwise, for someone who will look at it in the future, it is really hard to understand. Just keep everything simple and under stable. :wink:

**Comment by brylie** [comment]
> @brylie do you have any recommendation for Git management? Are you using any useful tool to help us? 

I've opened a discussion thread for development tools and techniques

https://github.com/CiviWiki/OpenCiviWiki/discussions/1093

**Pull request closed without merging**
