### PR TITLE
moved all dependency related code

### LINKED ISSUE #1131: [FEAT] Move all dependency related code
### Description

Currently, the project uses a lot of dependency files which can be obtained from the provider's cloud/CDN 
The following dependencies must be removed and routed to their CDN\

Current Dependency list:
- [ ] Animate CSS
- [ ] Backbone JS
- [ ] JQuery.min.JS
- [ ] Less.min.js
- [ ] magicsuggest.min.css
- [ ] magicsuggest.min.js
- [ ] underscore.js

Reference for animate css 
[link](https://cdnjs.com/libraries/animate.css)

You can find other links for the above mentioned dependencies there and change them the following way

Currently it is routed this  way:
```html
<script type="text/javascript" src="{% static "dependencies/jquery.min.js" %}"></script>
```

It ideally should be
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Once completed delete the above mentioned dependency files and create a pull request

### PR DESCRIPTION
**Pull request by samr1ddh1**
Closes #1131 
This PR removes all the dependency files and routes it to CDN
Hey there , this is my first PR.

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
@samr1ddh1 We really appreciate your contribution, it'd be great if you assign it next time. I will review this PR

**Review by AbhijithGanesh — APPROVED** [review]

**Review by brylie — CHANGES_REQUESTED** [review]
Please also delete the dependency files from this project, since they are no longer needed. I.e., we don't want to keep the dependency files in our project source code, as they are quite large.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @samr1ddh1 for code

**Comment by realce2** [comment]
Well shoot - this was my first PR too and I got super confused over how this happened, I was just about to push.  Assignments are good, guess I'll find another one.

**Pull request merged**
