### PR TITLE
Fix deprecation warnings

### LINKED ISSUE #1426: Fix `notifications` deprecation errors
### Description

When running management commands, I see the following deprecation warnings.

```sh
/OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/base/models.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.8.0'):
/OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/views.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
OpenCiviWiki/.venv/lib/python3.10/site-packages/notifications/urls.py:9: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

### What should have happened?

There should be no deprecation errors when running management commands.

**Upstream issue**: https://github.com/django-notifications/django-notifications/issues/344

### PR DESCRIPTION
**Pull request by DamyanBG**
Fix #1426 
  
## Description
I filtered out deprecation warnings and now they are not visible.

### CODE REVIEW

**Comment by brylie** [comment]
@DamyanBG, thank you for this pull request.

Disabling *all* deprecation warnings may be a bit of a big hammer for this issue since deprecation warnings help warn us about parts of the code that will not function after a specified time.

I found an upstream bug report in the `django-notifications-hq` project related to the specific deprecation warnings from issue #1426: 

https://github.com/django-notifications/django-notifications/issues/344

**Comment by brylie** [comment]
I've closed this PR since we want to keep deprecation warnings working. Also, it seems like the solution will be to fix the code in the upstream `django-notifications` package, which I'm not sure we can commit to doing.

**Comment by DamyanBG** [comment]
> @DamyanBG, thank you for this pull request.
> 
> Disabling _all_ deprecation warnings may be a bit of a big hammer for this issue since deprecation warnings help warn us about parts of the code that will not function after a specified time.
> 
> I found an upstream bug report in the `django-notifications-hq` project related to the specific deprecation warnings from issue #1426:
> 
> [django-notifications/django-notifications#344](https://github.com/django-notifications/django-notifications/issues/344)

Yes, I opened the issue.

**Comment by brylie** [comment]
lol I didn't notice that :-)

OK, do you think we should try to help resolve that issue upstream? Also, what do you think about discussion #1434?

**Comment by DamyanBG** [comment]
I will take a look.

**Pull request closed without merging**
