### PR TITLE
Registermodels

### LINKED ISSUE #1419: Register admin for remaining models
We haven't registered all project models with the Django Admin, making it difficult to manage content in a centralized manner.

## Task

For each model in our project,
- [ ] register the model with the Django Admin, if not already registered

## Instructions

Start by reading the following guides.

- Django [working with the Django admin](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/) - necessary knowledge to create a pull request with your changes
- GitHub [about working with branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) - necessary knowledge for registering Django models with the Django admin site

The only files that should be changed are admin.py in each app. Look in the models.py for each app and compare it with the admin.py in the same app. Find any models that have not been registered in admin.py and add them.

## Resources

- https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#modeladmin-objects

### PR DESCRIPTION
**Pull request by TimOsahenru**
:warning: When contributing code, please make sure you claim any related issue before opening a pull request. We will then assign you to the task to let other developers know that it has been claimed.

Closes #1419 
  
## Description

Registered unregistered models in the admin.py file

### CODE REVIEW

**Comment by brylie** [comment]
@TimOsahenru, there are many unrelated changes in this pull request. Rather than sorting everything out, it would probably be easier to start a new branch from `develop` and re-apply your changes.

Should we close this pull request and start a fresh one?

**Comment by TimOsahenru** [comment]
Oops... oh please do close it and start another one.

So, do you mean I didn't solve the issue ?

if yes please will be patient to guide me on what to do, this is my first contribution to an open source project, apologies if I'm making some obvious mistake.

**Comment by brylie** [comment]
@TimOsahenru, all good. It's hard to see what is unique to this pull request amidst all the other changes.

For starters, start by reading the following guides.

- Django [working with the Django admin](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/)
- GitHub [about working with branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)

The only files that should be changed are `admin.py` in each app. Look in the `models.py` for each app and compare it with the `admin.py` in the same app. Find any models that have not been registered in `admin.py` and add them.

**Comment by TimOsahenru** [comment]
I'm very clear on the issue my challenge is the git side of it, I had to delete the branch I initially created, created a new one and made a PR I hope my changes are visible this time... and thanks for the valid feedback it means alot @brylie  🙏

**Pull request closed without merging**
