### PR TITLE
Bug fixes

### LINKED ISSUE #1171: [BUG] Fix Bugs when profile is being viewed
### Description

The serialization is not correct when the registered user tries to view their own profile

This comes from the serialization part of our code-base which can be viewed [here](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/views.py#L181-L245)

```py
thread_wiki_data = {
        "thread_id": thread_id,
        "title": Thread_filter.title,
        "summary": Thread_filter.summary,
        "image": Thread_filter.image_url,
        "author": {
            "username": Thread_filter.author.user.username,
            "profile_image": Thread_filter.author.profile_image_url,
            "first_name": Thread_filter.author.first_name,
            "last_name": Thread_filter.author.last_name,
        },
        "contributors": [
            Profile.objects.chip_summarize(a)
            for a in Profile.objects.filter(
                pk__in=civis.distinct("author").values_list("author", flat=True)
            )
        ],
        "category": {
            "id": Thread_filter.category.id,
            "name": Thread_filter.category.name,
        },
        "categories": [{"id": c.id, "name": c.name} for c in Category.objects.all()],
        "created": Thread_filter.created_date_str,
        "num_civis": Thread_filter.num_civis,
        "num_views": Thread_filter.num_views,
        "user_votes": [
            {
                "civi_id": act.civi.id,
                "activity_type": act.activity_type,
                "c_type": act.civi.c_type,
            }
            for act in Activity.objects.filter(
                thread=Thread_filter.id, account=req_acct.id
            )
        ],
    }
```

### What should have happened?

The serialization should return user appropriately

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Further details

image

### PR DESCRIPTION
**Pull request by AbhijithGanesh**
Closes #1171
This is a draft PR, many other changes are yet to be made. Please make this a draft

### CODE REVIEW

**Comment by gorkemarslan** [comment]
I've changed the status of this PR to be drafted as @AbhijithGanesh wants.

**Comment by AbhijithGanesh** [comment]
@gorkemarslan merge this since we have a new ticket on #1181

**Comment by brylie** [comment]
> merge this since we have a new ticket on #1181

@AbhijithGanesh this pull request is still in draft state. In order to merge pull requests, they should be marked as "ready for review" and have at least one approval.

**Comment by gorkemarslan** [comment]
Fixed by #1186

**Pull request closed without merging**
