### PR TITLE
1.0 release

### PR DESCRIPTION
**Pull request by brylie**
Preparing to merge the development work for the 1.0 release.

### CODE REVIEW

**Comment by brylie** [comment]
@mdwest and @TomaszKolek, is there any ongoing work that you would like to get into the 1.0 release? This has been cooking for a long time, so I'd like to get it out of the oven.

**Comment by mdwest** [comment]
I agree, we are working on integrating the representative data using
govtracker. But I support a release.

However I defer to the group opinion on waiting for this update.

-mw

**Comment by brylie** [comment]
@mdwest can you check out the testing deployment for dev branch?
https://civiwiki-dev.herokuapp.com/

**Comment by brylie** [comment]
I will go ahead and merge these changes. Additional features can be developed in the 1.1 series. If there are backwards-incompatible changes, we will bump to 2.x.

**Comment by brylie** [comment]
@mdwest please add a review to this PR.

**Comment by brylie** [comment]
Waiting to make this release until #375 is resolved.

**Comment by brylie** [comment]
@mdwest please review this PR. You can test here:

https://civiwiki-dev.herokuapp.com/

**Comment by mdwest** [comment]
It was fixed when I tested last, but is broken again. Tomasz noted we need to:

**Comment by brylie** [comment]
@mdwest, can you obtain a ProPublica API key using the CiviWiki official email account?

I can try to trigger the migrations in Heroku deploy script.

**Comment by brylie** [comment]
It looks like the migration command just nreds to be added to the Procfile:

https://stackoverflow.com/a/39305091/1191545

**Comment by brylie** [comment]
@mdwest will you work with Tomasz to ensure the threads bug gets fixed? I will review the PR when it is opened.

**Comment by brylie** [comment]
@mdwest and @TomaszKolek I have configured Heroku to run migrations and added ProPublica API key as environment variable for all deployments. Please test and approve this PR, if it checks out.

**Comment by TomaszKolek** [comment]
Works for me!

**Comment by brylie** [comment]
@TomaszKolek I just resolved conflicts in this branch. Please do one more test, to make sure I didn't introduce any bugs when rebasing.

**Comment by brylie** [comment]
I can't see the linked Civis, so there may be a regression after the rebase. I think we should take this branch forward, though, and open a PR to fix the regression.

**Comment by TomaszKolek** [comment]
@brylie could you describe the issue for me please? is it something like:
1. Create a problem civi
2. Create a solution/cause civi
3. Solution and cause civi are not displayed
Is it right?

**Comment by brylie** [comment]
@TomaszKolek that is correct. Does the deployment look correct to you?

https://civiwiki-dev.herokuapp.com/

**Comment by TomaszKolek** [comment]
I've been investigating it for some time and IMHO it works fine. We have like 2 ways of displaying
"Others" and "Recommended" as Recommended we display problems + linked civis of problems that were voted by us. Is it right?

So once I vote on any problem and swtich to recommend I'm able to see civis that are linked to the problem

**Comment by brylie** [comment]
@all-contributors please add @danielgrijalva for code
@all-contributors please add @JonanOribe for code

**Comment by brylie** [comment]
@all-contributors please add @danielgrijalva for code

**Comment by brylie** [comment]
@all-contributors please add @JonanOribe for code

**Comment by brylie** [comment]
@all-contributors please add @terrencetuy for code

**Comment by brylie** [comment]
@all-contributors please add @dlarner3194 for code

**Comment by brylie** [comment]
@all-contributors please add @tomjohnhall for code

**Comment by brylie** [comment]
@all-contributors please add @jl24 for code

**Comment by brylie** [comment]
@all-contributors please add @GokuMizuno for code

**Comment by brylie** [comment]
@all-contributors please add @delta-plus for code

**Comment by brylie** [comment]
@all-contributors please add @WCollins3 for code

**Comment by brylie** [comment]
@all-contributors please add @ryan-barrett for code

**Comment by brylie** [comment]
@all-contributors please add @Sv3nman for code

**Comment by brylie** [comment]
@all-contributors please add @petarPetrovBG for code

**Comment by brylie** [comment]
@all-contributors please add @petarPetrovBG for test

**Comment by brylie** [comment]
@all-contributors please add @Unit111 for test

**Comment by brylie** [comment]
@all-contributors please add @mdwest for code, bug, business, financial, fundingFinding, ideas, projectManagement, review

**Comment by brylie** [comment]
@all-contributors please add @brylie for code, bug, projectManagement, review, doc, infra, maintenance

**Comment by brylie** [comment]
@all-contributors please add @TomaszKolek for code, test, security, review

**Comment by brylie** [comment]
@all-contributors please add @brylie for code, bug, projectManagement, review, doc, infra, maintenance

**Comment by brylie** [comment]
@all-contributors please add @brylie for code, bug, projectManagement, review, doc, infra, maintenance

**Comment by brylie** [comment]
@all-contributors please add @mdwest for code, bug, business, financial, fundingFinding, ideas, projectManagement, review

**Comment by brylie** [comment]
@all-contributors please add @Unit111 for test

**Comment by brylie** [comment]
@all-contributors please add @petarPetrovBG for test

**Comment by brylie** [comment]
@all-contributors please add @Sv3nman for code

**Comment by brylie** [comment]
@all-contributors please add @ryan-barrett for code

**Comment by brylie** [comment]
@all-contributors please add @WCollins3 for code

**Comment by brylie** [comment]
@all-contributors please add @jl24  for code, bug, doc, ideas, infra

**Comment by brylie** [comment]
@all-contributors please add @jl24 for question

**Comment by brylie** [comment]
@all-contributors please add @jl24 for code, bug, doc, ideas, infra, question

**Comment by brylie** [comment]
@all-contributors please add @delta-plus for code, bug, doc, ideas, question

**Comment by brylie** [comment]
@all-contributors please add @GokuMizuno for code, bug, ideas

**Comment by brylie** [comment]
@all-contributors please add @brylie for code, bug, projectManagement, review, doc, infra, maintenance

**Comment by brylie** [comment]
@all-contributors please add @dborstelmann for code, bug, infra, ideas

**Comment by brylie** [comment]
@all-contributors please add @DCalliet for code, bug, ideas

**Comment by brylie** [comment]
@all-contributors please add @tractaylor for code, bug, ideas

**Comment by brylie** [comment]
@all-contributors please add @tomjohnhall for code

**Comment by brylie** [comment]
@all-contributors please add @jstrang for code

**Comment by brylie** [comment]
@all-contributors please add @danielgrijalva for code

**Comment by brylie** [comment]
@all-contributors please add @g1stavo for code

**Comment by brylie** [comment]
@all-contributors please add @pscheid2 for code, ideas, question

**Comment by brylie** [comment]
@all-contributors please add @terrencetuy for code

**Comment by brylie** [comment]
@all-contributors please add @JonanOribe for code

**Comment by brylie** [comment]
@all-contributors please add @shaunak-gupta for code

**Comment by brylie** [comment]
@all-contributors please add @darcymeyer for code

**Comment by brylie** [comment]
@all-contributors please add @Jazriel for code

**Comment by brylie** [comment]
@all-contributors please add @therohitramesh for code

**Pull request merged**
