### PR TITLE
Html id tags added

### LINKED ISSUE #130: Add ID to logout button
Our automated testing is trying to access the logout button to make sure it works properly. However, this is made slightly brittle by the fact that the logout button does not have an ID.

# Task
- [ ] Logout button has meaningful (unique) ID

### LINKED ISSUE #131: Add ID to 'settings' button
Our automated testing is trying to access the 'settings' button to make sure it works properly. However, this is made slightly brittle by the fact that the 'settings button does not have an ID.

# Task
- [ ] 'Settings' button has meaningful (unique) ID

### LINKED ISSUE #134: Add ID to 'edit profile' button
Our automated testing is trying to access the 'edit profile' button to make sure it works properly. However, this is made slightly brittle by the fact that the 'edit profile' button does not have an ID.

# Task
- [ ] 'Edit profile' button has meaningful (unique) ID

### LINKED ISSUE #137: Add ID to 'trending issues' list title
Our automated testing is trying to access the 'trending issues' list to make sure it is visible on the page. However, this is made slightly brittle by the fact that the list title does not have an ID.

# Task
- [ ] 'Trending issues' list title has meaningful (unique) ID

### LINKED ISSUE #139: Add ID to 'add cause' button
Our automated testing is trying to access the 'add cause' button to make sure it works properly. However, this is made slightly brittle by the fact that the button does not have an ID.

# Task
- [ ] 'Add cause' button has meaningful (unique) ID

### LINKED ISSUE #140: Add ID to 'add solution' button
Our automated testing is trying to access the 'add solution' button to make sure it works properly. However, this is made slightly brittle by the fact that the button does not have an ID.

# Task
- [ ] 'Add solution' button has meaningful (unique) ID

### LINKED ISSUE #143: Add ID to 'thread category' dropdown
Our automated testing is trying to access the 'thread category' dropdown to make sure it works properly. However, this is made slightly brittle by the fact that the button does not have an ID.

# Task
- [ ] 'Thread category' dropdown has meaningful (unique) ID

### PR DESCRIPTION
**Pull request by mattyg915**
Fixes #130 
Fixes #134
Fixes #143
Fixes #137
Fixes #131

### CODE REVIEW

**Comment by brylie** [comment]
Is this mod a work in progress?

**Comment by brylie** [comment]
Please only add "Fixes #"s to issues this PR contains code for. Even if you are planning to fix them in this PR, we may risk accidentally closing issues that aren't actually fixed. Also, some work is ongoing in other PRs.

**Comment by mattyg915** [comment]
I had only added the fix tags for issues that I had actually fixed in the two commits that I made, are they not showing up as fixed (like in the actual code)?

**Comment by brylie** [comment]
Check issue #140

**Comment by mdwest** [comment]
Will this close

**Pull request merged**
