### PR TITLE
Worked on create file and delete task of  - Create project base template (base.html) #1049

### PR DESCRIPTION
**Pull request by SachinHatikankar100**
Hi,

I have worked on the below 2 tasks
1. delete the file: https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/templates/threads/base/links.html

2. delete all references to the threads/base/links.html
 https://github.com/CiviWiki/OpenCiviWiki/search?q=%7B%25+include+%22base%2Flinks.html%22+%25%7D

Note: I am learning open-source contribution. If there are any issues with the PR, please let me know. I will improve it accordingly.

Works on #1049

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
I shall review the changes 😄

**Comment by AbhijithGanesh** [comment]
Can you please mention me once all changes have been proposed? @SachinHatikankar100 and @PareshHK

**Comment by SachinHatikankar100** [comment]
@AbhijithGanesh Sure will do that :)

**Comment by SachinHatikankar100** [comment]
@AbhijithGanesh I was able to work on 2 mentioned task. Can you please review.

Also, I am unable to contribute to documentation guide as I understand django expertise is required for the same. I will continue to go through the issues and contribute if I feel confident 😊

**Comment by AbhijithGanesh** [comment]
I'll review them and patch those changes which you were unable to😃. All contributions matter and you'll learn soon dw😊

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
Can you inherit the template html wherever you can?

**Comment by SachinHatikankar100** [comment]
@AbhijithGanesh How to do it? Can you please help me with the steps? Need some guidance here

**Comment by AbhijithGanesh** [comment]
I'll explain tommorow

**Comment by brylie** [comment]
@AbhijithGanesh please link this pull request to the relevant issue.

**Comment by brylie** [comment]
@AbhijithGanesh, would you kindly assist @SachinHatikankar100 with resolving the conflicts in this branch?

**Comment by AbhijithGanesh** [comment]
I will help him, I forgot this PR yesterday, I'll help

**Comment by SachinHatikankar100** [comment]
Hi @AbhijithGanesh  not sure how we can connect to resolve the issues. I will be free in late evening after 8 PM IST FYI

**Comment by AbhijithGanesh** [comment]
@SachinHatikankar100 Do you know how to resolve conflicts? Otherwise I can help you with the necessary documentation

**Comment by AbhijithGanesh** [comment]
> 
> 
> @AbhijithGanesh How to do it? Can you please help me with the steps? Need some guidance here

To inherit and extend html, django provides an amazing feature through its template syntax, you can find them here
[Django Template Inheritance](https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-inheritance)

**Comment by SachinHatikankar100** [comment]
Hi @AbhijithGanesh Let me give a try. I will go through the documentation. Will highlight it here if I am unable to resolve the conflicts 😊

**Comment by SachinHatikankar100** [comment]
Hi, As Django is new for me it's taking more time for me as of now. Hence, unable to contribute. Apologies @brylie @AbhijithGanesh.
I Will contribute soon after learning Django

**Comment by brylie** [comment]
Take your time @SachinHatikankar100, we aren't in a rush. We really appreciate your willingness to contribute your time to CiviWiki :smiley: :guitar:

**Comment by AbhijithGanesh** [comment]
We appreciate your effort @SachinHatikankar100 , please take it slow .

**Comment by AbhijithGanesh** [comment]
We appreciate your effort @SachinHatikankar100 , please take it slow .

**Comment by AbhijithGanesh** [comment]
I really have a trouble with GitHub Mobile, 😐

**Review by AbhijithGanesh — APPROVED** [review]

**Comment by AbhijithGanesh** [comment]
@brylie Changes have been approved, @SachinHatikankar100 can you resolve conflicts

**Comment by SachinHatikankar100** [comment]
Hi @AbhijithGanesh . Sure. I will have a look and get back if required

**Comment by SachinHatikankar100** [comment]
Hi @AbhijithGanesh if I have to contribute then ideally I have follow the steps mentioned to run the project locally right?

**Comment by AbhijithGanesh** [comment]
Ideally yes, you might run into some error because of version differences, so if that happens let me know.

**Comment by SachinHatikankar100** [comment]
Hi @AbhijithGanesh today I am able to run the project locally without any issues. I have also registered in fact with a hope to get access/see the listed conflicted HTML files. 
Questions: 
1. Upon clicking in on "My Profile" I get the page with the message ``` The requested resource was not found on this server.```
2. Can you please guide how can I start resolving them? If the project has been correctly set up in my machine.

**Comment by AbhijithGanesh** [comment]
Did you pull the changes that has been made?

**Comment by SachinHatikankar100** [comment]
I have not pulled any changes. So far I have just run the project locally and tried to check if I can see the listed conflicted HTML pages

**Comment by AbhijithGanesh** [comment]
I think you should pull otherwise changes would be out of sync and it might be a bad PR

**Comment by AbhijithGanesh** [comment]
Also you need to resolve conflicts , please read [the docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Comment by brylie** [comment]
I'm converting this pull request to draft status since there is still work in progress.

**Comment by gorkemarslan** [comment]
Fixed by #1099 and #1117.

**Pull request closed without merging**
