### PR TITLE
Landing Page - Make Requested Changes

### PR DESCRIPTION
**Pull request by rdhoge**
Closes #1420
  
## Description
Addresses requests to add translate tags and clean up CSS code for pull request #1420.

### CODE REVIEW

**Review by brylie — CHANGES_REQUESTED** [review]
This looks good so far. Would you upload a screenshot of the new front page rendered in your local development environment?

**Comment by rdhoge** [comment]
Screenshots of front page

Screen Shot 2022-11-15 at 7 01 51 AM
Screen Shot 2022-11-15 at 7 02 01 AM
Screen Shot 2022-11-15 at 7 02 45 AM

**Review by brylie — CHANGES_REQUESTED** [review]
This looks good. Please make sure to resolve the conflicts so we can merge this PR.

**Comment by rdhoge** [comment]
Conflicts resolved.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @rdhoge for code

**Comment by brylie** [comment]
@all-contributors please add @ApoorvaKashyap for code

**Pull request merged**
