### PR TITLE
Update django-notifications (Closes #1244)

### LINKED ISSUE #1244: Update django-notifications-hq
Since the current version of `django-notifications-hq` is not compatible with `Django 4` and the new release of this package seems not possible for now, we can adjust the `requirements` of this project so that `requirements` contains the commit number that solves compatibility with `Django 4`, rather than the release version.

### PR DESCRIPTION
**Pull request by gorkemarslan**
Closes #1244

I prefer to keep the current version of `django-notifications` commented.

After adjusting this package, we can update `Django 3.2.10` to `4`. For sure, we have to make small changes but they are not big issues.

### CODE REVIEW

**Comment by gorkemarslan** [comment]
@brylie, I was aiming to keep Python updated and the latest version but this seems a mistake. First, Python `3.10.0` was updated to `3.10.1` and then updated again to `3.10.2`.

What do you suggest? Should we adjust the version of Python to be  `3.9.10` or maybe `3.8.12`? Otherwise, Python will be constantly updated and we have to set the project each time.

**Comment by brylie** [comment]
My preference for development environments is to specify a minimum compatible Python version (e.g. `^3.8`, as is done in [Poetry](https://python-poetry.org/docs/dependency-specification/#version-constraints). That way, developers can use whatever version of Python is compatible and available on their machine.

**Comment by gorkemarslan** [comment]
I understand @brylie.

I will fix the Python version problem to reopen #1235. And I will decrease it to `3.8` in a short time. Sorry for the appearing problem. 😅

**Comment by brylie** [comment]
All good :-)

Thanks for your continued stewardship of the CiviWiki project

**Comment by gorkemarslan** [comment]
@brylie now I see a huge migration of Python developers who start using Poetry. In the future, we might also introduce Poetry in our project.

**Review by brylie — APPROVED** [review]

**Pull request merged**
