### PR TITLE
Improved Social Profile

### PR DESCRIPTION
**Pull request by HushOv**

### CODE REVIEW

**Comment by brylie** [comment]
This PR deletes a lot of lines from our contributors list. Please re-open the PR with only the correct line(s) of change.

**Comment by brylie** [comment]
When opening a pull request, please provide a description. That way, we know why the changes are desired. Ideally, there would also be a relevant issue to describe the pull request.

**Comment by brylie** [comment]
Sorry to be a hassle, but can you please 
1. close this PR
2. create a clean branch
3. make your change and commit
4. open a fresh PR?

That way, this pull request will reflect only the change you made.

**Comment by HushOv** [comment]
Thanks

**Pull request closed without merging**
