### PR TITLE
Standardize Navigation

### LINKED ISSUE #68: While looking over the beta site, I had a difficult time finding where to go to manage my settings
Looking around the beta site, I was trying to find where to edit my account settings.  I was on the phone with Mitchell and ended up asking him.  

With it being a button with a + graphic, it made me think it was to add something, not edit my profile.  

I had thought the "Manage" button on the feed page would get me to a managed my user acct page.

### LINKED ISSUE #76: Thread View Frontend Issues
The current thread view is clunky and confusing to interact with and improvements are necessary.

# Tasks
From #73 
1. Entering a Civi Thread
- [ ]  Delete the thread landing page and instead go to the main content page right away
- [ ]  Limit content to fit within the bounding box of the feed page
2. Civi Creation
- [ ]  When Problem/Cause/Solution Civi type selected, Display only Civies which can be linked to the type of Civi being created (if cause then link to problem, if solution then link to cause)
3. Civi Linking
- [ ]  Rather than typing the title of a Civi you want to link, allow the user to select a button to link a to other Civies, then click one one more civies from the list of relevant Civies displayed.

### PR DESCRIPTION
**Pull request by jl24**
Resolves #68 
Resolves #76
Global navigation changed from floating circle buttons to a standard navbar at the top
- Top Left: CiviWiki Logo that redirects to the root url
- Top Right: Notification icon + Login user image & first name that opens a dropdown nav when clicked. 

screen shot 2017-09-12 at 7 03 02 am
screen shot 2017-09-12 at 7 03 56 am

### CODE REVIEW

**Comment by brylie** [comment]
@jl24 is this ready for review?

**Comment by jl24** [comment]
@brylie Navigation part is resolved, but access to settings is still somewhat hidden in the profile page. I don't like this secondary layer, and I believe settings should be moved to a separate page and added onto the navigation dropdown. Items related to the user, security, and, account access would be in the new page, while the profile page will only have edit options for profile image and personal bio.

**Comment by brylie** [comment]
Cool, just add the 'ready for review' label when you feel this PR is ready :smile_cat:

**Comment by jl24** [comment]
In addition to some ui chances, also resolves #76

**Comment by jl24** [comment]
##Changes:
- Global nav changed from floating to fixed top nav bar
- Creation of a separate user settings page accessible in the dropdown menu of the tab bar
- Timeout exception handler for the sunlight api
- UI changes to simplify the thread page
- Change thread entry to be the main thread body 
- Fix a bug where the ability to scroll was lost on the 3rd responses column when new civi was clicked (mostly an issue with short height windows)
- Problems cannot link to any civis
- Causes can only link to problems
- Solutions can only link to Causes
- Clinking in the Link Civi Input now automatically toggles the linkable list for ease of access

**Pull request merged**
