### PR TITLE
Update forms.py

### LINKED ISSUE #1016: User object not retrieved.
### Description

When I try running the project locally and I try registering a user, It shows an error.

### What should have happened?

I expect the registration to work successfully.

### What browser(s) are you seeing the problem on?

_No response_

### Further details

image
image

### PR DESCRIPTION
**Pull request by gorkemarslan**
Fixes #1016 

A further update is needed after my last PR.

### CODE REVIEW

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
Although it might not be relevant in this particular case, remember to use "Closes #<issue_number>" or "Fixes #<issue_number>" in order to link pull requests to the issues they close.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).
>
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
Can you please use the model in the meta class, is there any downside to it?

**Comment by gorkemarslan** [comment]
`get_user_model()` method gives you which user model is used in the project. It returns `AUTH_USER_MODEL` from the `settings.py`. In our case, it is defined such that

https://github.com/CiviWiki/OpenCiviWiki/blob/da0ad36db74b992efc7acc31823eb05bffe5582f/project/core/settings.py#L172

If `AUTH_USER_MODEL` were not specified here, the default Django `User` model is used for `get_user_model()`.

We shouldn't import the user model directly because there might be circular dependency issues, especially for ForeingKey and Many-to-Many fields usages.

This way is also recommended by Django official [docs](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#django.contrib.auth.get_user_model).

**Comment by AbhijithGanesh** [comment]
Points well noted, thanks for clarification,

**Pull request merged**
