### PR TITLE
removed us related code

### PR DESCRIPTION
**Pull request by ssabhijith2000**

### CODE REVIEW

**Comment by brylie** [comment]
When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Comment by AbhijithGanesh** [comment]
I shall review this asap Brylie.

**Comment by AbhijithGanesh** [comment]
This PR closes #1106

**Comment by AbhijithGanesh** [comment]
@brylie this PR was supposed to be from @xsraut but it isn't .  Can I go ahead and review this or will this be rejected?

**Comment by brylie** [comment]
We welcome pull requests in submission order. So, @ssabhijith2000's contribution should take precedent here.

**Comment by AbhijithGanesh** [comment]
Yeah but I think assignments supersede PRs? They were assigned to the issue

**Comment by brylie** [comment]
Issue assignments don't always lead to code contributions. So, we would rather prioritize active code contributors.

**Review by AbhijithGanesh — COMMENTED** [review]
Please add CIVI_TYPES back to the models or remove them from models.py

**Comment by AbhijithGanesh** [comment]
Points well noted Brylie

**Comment by brylie** [comment]
In cases where there are two active contributors on a single task, we can help them work together to divide the task. Perhaps @ssabhijith2000 and @xsraut can discuss how to divide the task? Otherwise, let's continue to support @ssabhijith2000's ongoing efforts :-)

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
The model requires CIVI_TYPES and it is not US related, please add it back @ssabhijith2000 
[project/threads/models.py](File)

**Comment by brylie** [comment]
@AbhijithGanesh when reviewing this code, please refer to the checklist in #1106. That way, your feedback will align with the task description.

**Comment by AbhijithGanesh** [comment]
Maybe yeah, we'll divide the issues

**Comment by brylie** [comment]
My bad, I got confused as to your message above.

@AbhijithGanesh, will you add line-level comments for any suggestions you propose? That way, we can understand exactly which line(s) are relevant.

https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

**Comment by AbhijithGanesh** [comment]
Apologies for the confusion, I don't know why this keeps happening

**Comment by brylie** [comment]
I think you were referring to the following line:

Peek 2021-10-11 12-40

For starters, try adding a single-line comment (the left button). 


As you get more comfortable with reviews, you can use the "start review" button (on the right), which requires that you "add review" once all of your comments are added.

https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#about-reviewing-pull-requests

As you review more pull requests, the workflow will become second nature :-)

**Comment by brylie** [comment]
> Apologies for the confusion, I don't know why this keeps happening

The confusion was my own. I just misread your comment. In any case, let's use the line-level comments to improve the clarity of feedback :-)

**Comment by brylie** [comment]
I'm converting this pull request to draft status since there is still work in progress. Please resolve conflicts.

**Comment by gorkemarslan** [comment]
Fixed by #1141

**Pull request closed without merging**
