### PR TITLE
Migration of thread url to path (closes #1077)

### LINKED ISSUE #1077: Migrate threads urls to path
in `threads` app, we need to change `url()`  function with `path()` function as discussed in #1066

https://github.com/CiviWiki/OpenCiviWiki/blob/d7f24fad7c0a2565da3bf2cd54e89a847d7479dd/project/threads/urls.py#L19-L41

Conversion to [path](https://github.com/CiviWiki/OpenCiviWiki/blob/d7f24fad7c0a2565da3bf2cd54e89a847d7479dd/project/threads/urls.py#L19-L41) is simple.

For example,

```python
url(r"^thread_data/(?P<thread_id>\w+)/$", get_thread, name="get thread"),
```

should become

```python
path("thread_data/(<int:thread_id>/", get_thread, name="get thread"),
```

We need to be changed all usages of `url()` function in `threads` app.

### PR DESCRIPTION
**Pull request by rishabhjha708**
Closes #1077

### CODE REVIEW

**Comment by gorkemarslan** [comment]
@rishabhjha708, while we are reviewing your PR, could you edit your PR message to add one of these [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)?

> Linking a pull request to an issue using a keyword
> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message (please note that the pull request must be on the default branch).
> 
> close
> closes
> closed
> fix
> fixes
> fixed
> resolve
> resolves
> resolved

**Review by gorkemarslan — APPROVED** [review]

**Comment by AbhijithGanesh** [comment]
Gorkem can you please run checks next time?

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
Please add them in urlpatterns rather than adding them in line 24

**Comment by rishabhjha708** [comment]
> Please add them in urlpatterns rather than adding them in line 24

Can you please elaborate @AbhijithGanesh

**Comment by AbhijithGanesh** [comment]
Can you make it a single list of all urlpatterns instead of appending them? Is there a need to append them with this convention of Django

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, could you explain this more? 😅 
> Gorkem can you please run checks next time?

```python
urlpatterns = [
    path("v1/", include(router.urls)),
]
```
This usage is also Ok because this URL is related to API part. URLs of web pages are added to it:

```python
urlpatterns += [
...
]
```

Next time, a new issue will be created to split API and web page urls. 😉 
> Please add them in urlpatterns rather than adding them in line 24

**Comment by AbhijithGanesh** [comment]
I meant when you're reviewing a new contributor's work, if you feel they're good to go, can you please run automated checks?
@gorkemarslan

**Comment by rishabhjha708** [comment]
Hi @gorkemarslan @AbhijithGanesh , should I make changes ??

**Comment by AbhijithGanesh** [comment]
I agree with the part where that usage is okay but I don't think there was a need for that?  If there was a genuine need of a separate list appended at the end, I'll approve the changes right now but other wise I thought one list will be simple and easy to read.

**Review by AbhijithGanesh — APPROVED** [review]

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, according to issue #1030, we need to register api-related parts for the general router. A new issue will be about registering api urls to `CiviWikiRouter`.

**Comment by AbhijithGanesh** [comment]
Understood that and approved these changes.

**Pull request merged**
