### PR TITLE
Disabled Auto-Named Migration 

### LINKED ISSUE #1351: disable auto-named migration
## Task

- [ ] create a file `project/core/management/commands/makemigrations.py` with the following content

```py
from django.core.management.base import CommandError
from django.core.management.commands.makemigrations import (
    Command as BaseCommand,
)


class Command(BaseCommand):
    def handle(self, *app_labels, name, dry_run, merge, **options):
        if name is None and not dry_run and not merge:
            raise CommandError("-n/--name is required.")
        
        super().handle(
            *app_labels,
            name=name,
            dry_run=dry_run,
            merge=merge,
            **options,
        )
```

### PR DESCRIPTION
**Pull request by simar5244**
Closes #1351 
Issue Tracked in #1342 

Added file makemigrations.py in project/core/management/commands/ to disable auto-named migrations

### CODE REVIEW

**Comment by brylie** [comment]
@simar5244, thank you for working on this task. Please add a comment in the related issue to claim it so other developers can see which tasks are available.

**Comment by simar5244** [comment]
@brylie can you take a look at exit code 1 error?

**Comment by brylie** [comment]
@simar5244, I will review this code once we have assigned you to the related issue. Please add a comment in issue #1351 so that I can assign you. That way, other developers know which tasks are available.

**Review by brylie — CHANGES_REQUESTED** [review]
@simar5244, I will review this code once we have assigned you to the related issue. Please add a comment in issue https://github.com/CiviWiki/OpenCiviWiki/issues/1351 so that I can assign you. That way, other developers know which tasks are available.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @simar5244 for code

**Pull request merged**
